trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/terraform/spoke-aks-prod/**
      - .azdo/pipelines/spoke-deploy.yml
      - .azdo/pipelines/templates/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/terraform/spoke-aks-prod/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.9'
  terraformPath: '$(System.DefaultWorkingDirectory)/infra/terraform/spoke-aks-prod'
  tfvarsFile: 'prod.tfvars'
  planFile: 'tfplan.prod'
  backendResourceGroup: 'rg-terraform-state'
  backendStorageAccount: 'tfstate'
  backendContainer: 'terraform'
  azureServiceConnection: 'Azure-Terraform-Connection'

stages:
  - stage: Validate
    displayName: '🔍 Validate Terraform'
    jobs:
      - job: ValidateConfig
        displayName: 'Validate Spoke Configuration'
        steps:
          - template: templates/terraform-validate.yml
            parameters:
              terraformPath: $(terraformPath)
              serviceConnection: $(azureServiceConnection)

  - stage: Init
    displayName: '⚙️  Initialize Terraform'
    dependsOn: Validate
    condition: succeeded()
    jobs:
      - job: InitBackend
        displayName: 'Initialize Terraform Backend'
        steps:
          - template: templates/terraform-init.yml
            parameters:
              terraformPath: $(terraformPath)
              backendResourceGroup: $(backendResourceGroup)
              backendStorageAccount: $(backendStorageAccount)
              backendContainer: $(backendContainer)
              serviceConnection: $(azureServiceConnection)

  - stage: Plan
    displayName: '📋 Plan Infrastructure Changes'
    dependsOn: Init
    condition: succeeded()
    jobs:
      - job: GeneratePlan
        displayName: 'Plan Spoke Infrastructure'
        steps:
          - template: templates/terraform-init.yml
            parameters:
              terraformPath: $(terraformPath)
              backendResourceGroup: $(backendResourceGroup)
              backendStorageAccount: $(backendStorageAccount)
              backendContainer: $(backendContainer)
              serviceConnection: $(azureServiceConnection)

          - template: templates/terraform-plan.yml
            parameters:
              terraformPath: $(terraformPath)
              tfvarsFile: $(tfvarsFile)
              planFile: $(planFile)
              serviceConnection: $(azureServiceConnection)

  - stage: Apply
    displayName: '🚀 Apply Infrastructure Changes'
    dependsOn: Plan
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: ApplyInfra
        displayName: 'Apply Spoke Infrastructure'
        environment: 'Spoke-Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - template: templates/terraform-init.yml
                  parameters:
                    terraformPath: $(terraformPath)
                    backendResourceGroup: $(backendResourceGroup)
                    backendStorageAccount: $(backendStorageAccount)
                    backendContainer: $(backendContainer)
                    serviceConnection: $(azureServiceConnection)

                - template: templates/terraform-plan.yml
                  parameters:
                    terraformPath: $(terraformPath)
                    tfvarsFile: $(tfvarsFile)
                    planFile: $(planFile)
                    serviceConnection: $(azureServiceConnection)

                - template: templates/terraform-apply.yml
                  parameters:
                    terraformPath: $(terraformPath)
                    planFile: $(planFile)
                    serviceConnection: $(azureServiceConnection)
