# CI/CD Landing Zone Deployment Pipeline
# Deploys CI/CD Terraform code per .github/instructions/cicd-deploy.instructions.md
#
# Prerequisites:
#   1. Run scripts/setup-ado-pipeline.sh to create ARM service connection + Platform KV
#   2. Set pipeline variable PLATFORM_KV_ID to the platform Key Vault resource ID
#   3. (Optional) Hub deployed — populate hub variables in prod.tfvars for Day 2 integration
#
# First run: Set USE_SELF_HOSTED=false (or leave unset) to use MS-hosted agents.
# After agents are deployed and registered in ADO, set USE_SELF_HOSTED=true.

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/terraform/cicd/**

# Pool selection: set USE_SELF_HOSTED to 'true' (ADO pipeline variable) after agents
# are deployed and registered. First run uses MS-hosted agents (bootstrap).
${{ if eq(variables['USE_SELF_HOSTED'], 'true') }}:
  pool:
    name: 'aci-cicd-pool'
${{ if ne(variables['USE_SELF_HOSTED'], 'true') }}:
  pool:
    vmImage: 'ubuntu-latest'

variables:
  - name: TF_WORKING_DIR
    value: 'infra/terraform/cicd'
  - name: ENVIRONMENT
    value: 'prod'
  - name: ARM_USE_OIDC
    value: 'true'
  - name: TF_VAR_FILE
    value: 'prod.tfvars'
  - name: BACKEND_CONFIG
    value: 'backend-prod.tfbackend'

stages:
  - stage: Validate
    displayName: 'Terraform Validate'
    jobs:
      - job: Validate
        displayName: 'Format & Validate'
        steps:
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.14.5'

          - task: AzureCLI@2
            displayName: 'Terraform Init & Validate'
            inputs:
              azureSubscription: 'azure-cicd-prod'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              addSpnToEnvironment: true
              inlineScript: |
                export ARM_CLIENT_ID=$servicePrincipalId
                export ARM_TENANT_ID=$tenantId
                export ARM_OIDC_TOKEN=$idToken
                export ARM_USE_OIDC=true
                export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

                cd $(TF_WORKING_DIR)

                terraform init -backend-config=$(BACKEND_CONFIG)
                terraform fmt -check -recursive
                terraform validate

  - stage: Plan
    displayName: 'Terraform Plan'
    dependsOn: Validate
    jobs:
      - job: Plan
        displayName: 'Generate Plan'
        steps:
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.14.5'

          - task: AzureCLI@2
            displayName: 'Terraform Plan'
            inputs:
              azureSubscription: 'azure-cicd-prod'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              addSpnToEnvironment: true
              inlineScript: |
                export ARM_CLIENT_ID=$servicePrincipalId
                export ARM_TENANT_ID=$tenantId
                export ARM_OIDC_TOKEN=$idToken
                export ARM_USE_OIDC=true
                export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

                cd $(TF_WORKING_DIR)

                terraform init -backend-config=$(BACKEND_CONFIG)
                terraform plan \
                  -var-file="$(TF_VAR_FILE)" \
                  -var="platform_key_vault_id=$(PLATFORM_KV_ID)" \
                  -out=tfplan \
                  -input=false

          - publish: $(TF_WORKING_DIR)/tfplan
            artifact: tfplan
            displayName: 'Publish Plan Artifact'

  - stage: Apply
    displayName: 'Terraform Apply'
    dependsOn: Plan
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Apply
        displayName: 'Apply Infrastructure'
        steps:
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.14.5'

          - download: current
            artifact: tfplan
            displayName: 'Download Plan Artifact'

          - task: AzureCLI@2
            displayName: 'Terraform Apply'
            inputs:
              azureSubscription: 'azure-cicd-prod'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              addSpnToEnvironment: true
              inlineScript: |
                export ARM_CLIENT_ID=$servicePrincipalId
                export ARM_TENANT_ID=$tenantId
                export ARM_OIDC_TOKEN=$idToken
                export ARM_USE_OIDC=true
                export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

                cd $(TF_WORKING_DIR)

                terraform init -backend-config=$(BACKEND_CONFIG)
                terraform apply -input=false $(Pipeline.Workspace)/tfplan/tfplan

          - script: |
              cd $(TF_WORKING_DIR)
              POOL_NAME=$(terraform output -raw agent_pool_name)
              echo "=== Post-Deployment: Agent Pool Registration ==="
              echo "Register the UAMI in Azure DevOps:"
              echo "  1. Go to ADO → Organization Settings → Agent Pools"
              echo "  2. Create pool '${POOL_NAME}' if it doesn't exist"
              echo "  3. Register the UAMI client ID with the pool"
              echo ""
              echo "Once agents are registered, update spoke-deploy.yml pool to:"
              echo "  pool:"
              echo "    name: '${POOL_NAME}'"
            displayName: 'Print Agent Registration Instructions'
